apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cron
spec:
  schedule: "0 0 * * *"  
  startingDeadlineSeconds: 30 
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600  
      template:
        metadata:
          labels:
            app: django
        spec:
          containers:
          - name: clearsessions
            image: django_app:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: secret_key
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: debug
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_url
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: allowed_hosts
            
          restartPolicy: Never
