apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: edu-reverent-mestorf
spec:
  selector:
    project: django
  ports:
  - nodePort: 30291
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort