apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
        namespace: edu-reverent-mestorf
    spec:
      containers:
      - name: django-back
        image: turnsourcream823/django_app:latest
        envFrom:
        - secretRef:
            name: django-secret  
        volumeMounts:
        - name: postgres-cert
          mountPath: /etc/ssl/certs/
        ports:
        - containerPort: 80
      volumes:
      - name: postgres-cert
        secret:
          secretName: postgres-cert