apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: make-migrations
        image: turnsourcream823/django_app:latest
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - secretRef:
            name: django-secret  
        volumeMounts:
        - name: postgres-cert
          mountPath: /etc/ssl/certs/
        ports:
        - containerPort: 80
      volumes:
      - name: postgres-cert
        secret:
          secretName: postgres-cert
