version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-test_k8s}
      POSTGRES_USER: ${POSTGRES_USER-test_k8s}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}
    ports:
      - 5433:5432

  web:
    build: backend_main_django
    image: django_app
    volumes:
      - ./backend_main_django:/code
    environment: 
      SECRET_KEY: ${WEB_SECRET_KEY-REPLACE_ME}
      DEBUG: ${WEB_DEBUG-TRUE}
      DATABASE_URL: ${WEB_DATABASE_URL-postgres://test_k8s:OwOtBep9Frut@192.168.0.11:5433/test_k8s}
      ALLOWED_HOSTS: ${WEB_ALLOWED_HOSTS-127.0.0.1,localhost,192.168.59.101}
    ports:
      - 127.0.0.1:8080:80
      - 192.168.0.104:8080:80
    depends_on:
      - db

volumes:
  db_data: