apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-reverent-mestorf
  labels:
    project: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
